chore: set prisma
nowisf/true pull request #9
Opened 2023-01-29 21:33 UTC by nowisf

2023-01-30 13:22 UTC, juanlatorre commented on prisma/schema.prisma
> +  createdAt DateTime
```suggestion
  createdAt DateTime @default(now())
```

2023-01-30 13:23 UTC, juanlatorre commented on prisma/schema.prisma
> +  updatedAt DateTime
```suggestion
  updatedAt DateTime @default(now()) @updatedAt
```

2023-01-30 14:09 UTC, juanlatorre requested changes
Faltan algunas cositas, dejé algunos comentarios

2023-01-30 14:09 UTC, juanlatorre commented on prisma/schema.prisma
> +model Vote {
falta 

```
createdAt               DateTime                 @default(now())
updatedAt               DateTime?                @default(now()) @updatedAt
deletedAt               DateTime?
```

2023-01-31 17:28 UTC, nowisf commented on prisma/schema.prisma
> +model Vote {
added

2023-01-31 17:34 UTC, juanlatorre approved these changes
gj 🚀

2023-01-31 17:34 UTC, juanlatorre commented on prisma/schema.prisma
> +  updatedAt DateTime  @default(now()) @updatedAt
```suggestion
  updatedAt DateTime?  @default(now()) @updatedAt
```

2023-01-31 17:35 UTC, merged